import React from 'react'

let { forwardRef } = React

let styleProps = {
  margin: true,
  m: true,
  marginTop: true,
  mt: true,
  marginRight: true,
  mr: true,
  marginBottom: true,
  mb: true,
  marginLeft: true,
  ml: true,
  marginX: true,
  mx: true,
  marginY: true,
  my: true,
  padding: true,
  p: true,
  paddingTop: true,
  pt: true,
  paddingRight: true,
  pr: true,
  paddingBottom: true,
  pb: true,
  paddingLeft: true,
  pl: true,
  paddingX: true,
  px: true,
  paddingY: true,
  py: true,
  color: true,
  bg: true,
  backgroundColor: true,
  fontFamily: true,
  fontSize: true,
  fontWeight: true,
  lineHeight: true,
  letterSpacing: true,
  textAlign: true,
  fontStyle: true,
  width: true,
  height: true,
  display: true,
  minWidth: true,
  minHeight: true,
  maxWidth: true,
  maxHeight: true,
  size: true,
  verticalAlign: true,
  overflow: true,
  overflowX: true,
  overflowY: true,
  alignItems: true,
  alignContent: true,
  justifyItems: true,
  justifyContent: true,
  flexWrap: true,
  flexDirection: true,
  flex: true,
  flexGrow: true,
  flexShrink: true,
  flexBasis: true,
  justifySelf: true,
  alignSelf: true,
  order: true,
  gridGap: true,
  gridColumnGap: true,
  gridRowGap: true,
  gridColumn: true,
  gridRow: true,
  gridAutoFlow: true,
  gridAutoColumns: true,
  gridAutoRows: true,
  gridTemplateColumns: true,
  gridTemplateRows: true,
  gridTemplateAreas: true,
  gridArea: true,
  backgroundImage: true,
  backgroundSize: true,
  backgroundPosition: true,
  backgroundRepeat: true,
  border: true,
  borderWidth: true,
  borderStyle: true,
  borderColor: true,
  borderRadius: true,
  borderTop: true,
  borderTopWidth: true,
  borderTopStyle: true,
  borderTopColor: true,
  borderTopLeftRadius: true,
  borderTopRightRadius: true,
  borderRight: true,
  borderRightWidth: true,
  borderRightStyle: true,
  borderRightColor: true,
  borderBottom: true,
  borderBottomWidth: true,
  borderBottomStyle: true,
  borderBottomColor: true,
  borderBottomLeftRadius: true,
  borderBottomRightRadius: true,
  borderLeft: true,
  borderLeftWidth: true,
  borderLeftStyle: true,
  borderLeftColor: true,
  borderX: true,
  borderY: true,
  position: true,
  zIndex: true,
  top: true,
  right: true,
  bottom: true,
  left: true,
  textShadow: true,
  boxShadow: true,
}

export function removeStyledProps(props) {
  debugger
  return Object.keys(props).reduce((acc, pName) => {
    if (!styleProps[pName]) {
      acc[pName] = props[pName]
    }
    return acc
  }, {})
}

export default forwardRef(({ as: Element, ...passedProps }, ref) => {
  let props = removeStyledProps(passedProps)
  console.log(props)
  throw new Error('Catch Here!!!!')
  return <Element ref={ref} {...props} />
})
